const p = (...parts) => parts.map(text => `<p>${text}</p>`).join("");
const feature = (key, name, level, description, group = "necromancer") => ({ key, name, level, description, group });

export const NECROMANCER_CLASS = {
  key: "necromancer",
  name: "Necromante — Nova Era",
  description: `<h2>Necromante</h2><blockquote>“A morte não é o fim. É o recurso mais poderoso que existe.”</blockquote>
  ${p("Conjurador completo de Inteligência que marca presas, colhe Essência Cadavérica, manipula cadáveres e comanda mortos-vivos.", "Dado de Vida: d8. Resistências: Inteligência e uma escolha permanente entre Sabedoria ou Constituição. Armaduras leves e armas simples.", "A lista de magias do Necromante será distribuída separadamente; esta classe usa a progressão completa de espaços até o 9º círculo.")}`
};

const improvement = level => feature(`necromancer-aprimoramento-${level}`, `Talento / Aumento de Atributo — Nível ${level}`, level, p("Receba um Talento ou Aumento de Atributo conforme as regras gerais de Nova Era."));

export const NECROMANCER_FEATURES = [
  feature("necromancer-spellcasting", "Conjuração do Necromante", 1, `<p>Inteligência é seu atributo de conjuração. CD = 8 + Proficiência + INT; ataque mágico = Proficiência + INT. Prepare um número de magias igual ao nível de Necromante + INT. Você utiliza um Foco Necromântico.</p><p>Essência Cadavérica e espaços de magia são recursos independentes.</p>`),
  feature("necromancer-cadaveric-essence", "Essência Cadavérica", 1, `<p>Seu máximo de Essência Cadavérica (EC) é <strong>Proficiência + INT</strong>. Um Descanso Longo restaura toda a EC.</p><p><strong>Colher a Morte:</strong> quando uma ameaça hostil válida percebida a até 9 m chega a 0 PV, recupere 1 EC; se era sua Marca de Morte, recupere +1 EC. ND 0 e criaturas criadas, invocadas ou controladas por você não geram EC.</p><p><strong>Sacrifício Profano — Ação Bônus:</strong> sofra 1d6 + INT de dano necrótico irredutível e intransferível para recuperar 1 EC. Usos iguais à Proficiência por Descanso Longo.</p>`),
  feature("necromancer-death-mark", "Marca de Morte", 1, `<p><strong>Ação Bônus • 18 m.</strong> Marque uma criatura percebida. Apenas uma Marca fica ativa; não exige Concentração e termina com a morte do alvo, sua Incapacitação, um Descanso Longo ou uma nova Marca.</p><p>Uma vez por turno, seu dano necrótico contra a Marca recebe +Proficiência. Uma vez em cada turno dos servos, o primeiro ataque de um morto-vivo escolhido contra ela tem Vantagem. A morte da Marca gera +1 EC adicional.</p>`),
  feature("necromancer-profane-touch", "Toque Profano", 1, `<p><strong>Ação • ataque mágico à distância • 18 m.</strong> Causa 1d8 + INT necrótico; 2d8 no nível 5, 3d8 no 11 e 4d8 no 17.</p><p>Ao atingir sua Marca, escolha: <strong>Atrair</strong> 3 m; <strong>Repelir</strong> 3 m; ou <strong>Enfraquecer</strong>, impedindo Ataques de Oportunidade contra você até o início do seu próximo turno.</p>`),
  feature("necromancer-lesser-reanimation", "Reanimação Menor", 2, `<p><strong>Ação • 3 m • 2 EC.</strong> Transforme um Cadáver Válido Pequeno ou Médio em Esqueleto ou Zumbi. Máximo: 2 servos nos níveis 2–4, 3 nos 5–8, 4 nos 9–12, 5 nos 13–16 e 6 nos 17–20.</p><p>Os servos agem juntos imediatamente após você. Uma vez por turno, emita gratuitamente uma Ordem: Atacar, Defender (+2 CA e não ataca), Avançar (Dash e Vantagem contra Ataques de Oportunidade), Recuar (Disengage e mover) ou Interagir.</p>`),
  feature("necromancer-skeleton", "Servo — Esqueleto Reanimado", 2, `<p>CA 12 + Proficiência; PV 5 + 3 × nível; deslocamento 9 m. Ataque = Proficiência + INT; dano 1d6 + Proficiência perfurante ou cortante.</p><p><strong>Ataque Calculado:</strong> uma vez por turno do grupo, um Esqueleto que atingir sua Marca causa +INT de dano.</p>`, "servants"),
  feature("necromancer-zombie", "Servo — Zumbi Reanimado", 2, `<p>CA 10 + Proficiência; PV 8 + 4 × nível; deslocamento 6 m. Ataque = Proficiência + INT; dano 1d6 + Proficiência.</p><p><strong>Carne Morta:</strong> reduza em Proficiência a primeira instância de dano por rodada. <strong>Interpor-se — Reação, 1/rodada:</strong> torne-se alvo de um ataque dirigido a criatura a até 1,5 m.</p>`, "servants"),
  improvement(4),
  feature("necromancer-corpse-explosion", "Explosão Cadavérica", 5, `<p><strong>Ação • 18 m • 2 EC.</strong> Destrua/exaura um Cadáver Válido ou morto-vivo sob seu controle. Criaturas num raio de 3 m fazem Destreza contra sua CD: 4d6 necrótico (6d6 no nível 11; 8d6 no 17), metade no sucesso. Um servo detonado não gera EC e seus restos ficam Exauridos.</p>`),
  feature("necromancer-improved-touch", "Toque Profano Aprimorado", 5, `<p>Ao atingir sua Marca com Toque Profano, escolha duas Manipulações diferentes. Você também aprende <strong>Profanar</strong>: o alvo não recupera PV até o início do seu próximo turno. Atrair e Repelir não podem ser combinados.</p>`),
  feature("necromancer-essence-extraction", "Extração de Essência", 6, `<p>Uma vez por turno, ao causar dano necrótico a hostil que permaneça com ao menos 1 PV, escolha uma opção: <strong>Drenar</strong>, recebendo PV temporários = Proficiência + INT; <strong>Alimentar</strong>, curando um morto-vivo controlado a 18 m em 1d8 + Proficiência + INT; ou <strong>Coletar</strong>, recuperando 1 EC (Proficiência usos/Descanso Longo).</p><p>Uma ocorrência de dano não pode produzir múltiplas Extrações.</p>`),
  feature("necromancer-death-presence", "Presença da Morte", 7, `<p><strong>Ação Bônus • 1 EC • aura 6 m • 1 minuto • sem Concentração.</strong> Hostis que entrem pela primeira vez no turno ou iniciem nele fazem Sabedoria. Falha: não realizam Reações e subtraem 1d4 da próxima salvaguarda enquanto permanecerem na aura.</p><p>Mortos-vivos controlados na aura recebem +1 CA; uma vez por turno do grupo, o primeiro acerto deles causa +metade da Proficiência, arredondada para cima.</p>`),
  improvement(8),
  feature("necromancer-unstable-body", "Corpo Instável", 9, `<p>Ao gastar 2 ou mais EC em seu turno, receba 1 Instabilidade, máximo 3. Ela termina após o combate ou 1 minuto sem gastar EC.</p><ol><li><strong>Carne Fria:</strong> resistência necrótica.</li><li><strong>Essência Transbordante:</strong> +1d8 necrótico uma vez por turno.</li><li><strong>À Beira da Morte:</strong> Vantagem contra medo e envenenamento; dano necrótico ignora resistência; ao sofrer Radiante, receba +Proficiência de dano.</li></ol><p><strong>Purgar Essência — Ação Bônus:</strong> reduza 1 Instabilidade e sofra 1d6 necrótico irredutível.</p>`),
  feature("necromancer-partial-lich", "Forma Lich Parcial", 10, `<p><strong>Ação Bônus • 2 EC • 1 minuto • 1/Descanso Longo.</strong> Fique em Instabilidade 3, ignorando sua penalidade Radiante. Para efeitos benéficos próprios, pode ser tratado como morto-vivo. Recebe resistência a Necrótico e Veneno, Visão no Escuro 36 m, Vantagem contra medo, doença e veneno e não precisa respirar.</p><p><strong>Recusa da Morte:</strong> uma vez na transformação, ao cair a 0 sem morte instantânea, fique com 1 PV. Hostis escolhidos a 3 m fazem CON: 3d8 necrótico e empurrão de 3 m na falha, metade sem empurrão no sucesso. Ao terminar, Instabilidade torna-se 1.</p>`),
  feature("necromancer-perfect-reanimation", "Reanimação Perfeita", 11, `<p><strong>Ritual de 1 hora; consome toda a EC atual, mínimo 5.</strong> Crie um único Cadáver Perfeito a partir de cadáver cujo ND não exceda metade do seu nível. Ele não conta no limite de servos menores.</p><p>PV = 10 + 6 × nível; CA apropriada do original, máximo 12 + Proficiência; ataques usam Proficiência + INT. Dois ataques nos níveis 11–16, três no 17–20. Dano médio por ataque: 10 (11–14), 12 (15–16), 14 (17–19), 16 (20).</p><p>Heranças: 2 espaços no 11, 3 no 15, 4 no 18; menores custam 1, maiores 2. Sem ações/resistências lendárias, ações de covil/míticas, conjuração completa, ressurreição ou invocação ilimitadas. A 0 PV fica Inerte; num Descanso Longo, 5 EC reconstrói os restos com PV total.</p>`),
  improvement(12),
  feature("necromancer-mass-harvest", "Colheita em Massa", 13, `<p>Quando sua Marca chega a 0 PV, além da EC normal escolha: <strong>Devorar Essência</strong>, +1 EC; <strong>Devorar Vida</strong>, você ou criatura percebida a 18 m cura 2d8 + INT; ou <strong>Grito dos Mortos</strong>, mortos-vivos a 18 m têm Vantagem no próximo ataque até o próximo turno deles e o primeiro acerto do grupo causa +1d8 necrótico.</p>`),
  feature("necromancer-death-bond", "Vínculo com a Morte", 14, `<p>Quando morto-vivo controlado a 18 m seria reduzido a 0, use sua Reação: <strong>Partilhar a Dor</strong> o deixa com 1 PV e você sofre metade do dano final, arredondado para cima, irredutível e intransferível; ou <strong>Recusar a Perda</strong>, gaste 2 EC, deixe-o com 1 PV e mova-o até metade sem Ataques de Oportunidade. Funciona com o Cadáver Perfeito.</p>`),
  feature("necromancer-dead-field", "Domínio do Campo Morto", 15, `<p><strong>Ação • 5 EC • ponto a 18 m • raio 6 m • 1 minuto • sem Concentração.</strong> Área fixa; apenas um Domínio por vez.</p><p>Hostis que entrem pela primeira vez no turno ou iniciem ali fazem CON: 2d8 necrótico, metade no sucesso, máximo uma ocorrência/rodada. Não recuperam PV. Seus mortos-vivos recebem +2 CA e Vantagem contra medo, Incapacitação e expulsão. Cadáveres dentro contam como a 18 m; Reanimação Menor alcança qualquer um deles; Explosão Cadavérica ali tem raio 4,5 m.</p>`),
  improvement(16),
  feature("necromancer-profane-transcendence", "Transcendência Profana", 17, `<p>Permanentemente: resistência necrótica, imunidade a Amedrontado e doenças, não precisa respirar, magia não o envelhece contra a vontade e Visão Verdadeira 18 m.</p><p><strong>Alimentar-se da Morte:</strong> uma vez por turno, ao recuperar EC pela morte de hostil, cure PV iguais à INT.</p>`),
  feature("necromancer-transcendent-touch", "Toque Transcendente", 17, `<p>Ao acertar sua Marca com Toque Profano, intensifique uma Manipulação: Atrair/Repelir 6 m; Enfraquecer também impõe −2 CA; Profanar também remove todos os PV temporários atuais.</p>`),
  feature("necromancer-infinite-army", "Exército Infinito", 18, `<p><strong>Ação • 6 EC • 1/Descanso Longo.</strong> Crie por 1 minuto uma Horda Cadavérica Enorme num ponto a 18 m, ocupando aproximadamente 6 × 6 m. CA 12 + Proficiência; PV 15 × Proficiência; seu espaço é terreno difícil para hostis.</p><p>No turno dos servos, hostis dentro fazem DEX contra <strong>Maré Cadavérica</strong>: 4d8 + INT necrótico, metade no sucesso; na falha podem ser derrubados ou arrastados 3 m. Uma vez por turno, morte hostil dentro cura a Horda em 2d8 + INT. A Horda não conta no limite menor.</p>`),
  improvement(19),
  feature("necromancer-death-avatar", "Avatar da Morte", 20, `<p><strong>Ação Bônus • 1 minuto • 1/Descanso Longo.</strong> Ative Forma Lich Parcial sem custo/uso e permaneça em Instabilidade 3. No início de cada turno recupere 3 EC; o primeiro gasto de EC do turno custa 2 a menos.</p><p>Presença da Morte fica gratuita, raio 12 m e também Amedronta até o início do turno seguinte. Toque Profano ataca dois alvos diferentes. Uma vez por criatura por Avatar, sua Marca terminando o turno com 30 PV ou menos faz CON: morre na falha ou sofre 6d10 necrótico no sucesso.</p><p>O Cadáver Perfeito recupera uma característica selada adaptada; uma ação lendária pode virar Reação 1/rodada. A primeira Recusa da Morte deixa você com nível + INT PV.</p>`)
];

export const NECROMANCER_PATHS = [
  { key: "path-soul-bleeder", name: "Caminho do Sangrador de Almas", description: p("Transforma vitalidade, dano necrótico e o próprio sangue em sobrevivência e Essência."), features: [
    feature("soul-thirst", "Sede de Alma", 3, `<p>Uma vez por turno, ao causar dano necrótico a criatura a 6 m, escolha: <strong>Devorar</strong>, receba PV temporários = Proficiência + INT; ou <strong>Sangrar</strong>, sofra Proficiência de dano irredutível para recuperar 1 EC.</p><p><strong>Olfato da Alma:</strong> saiba se criatura percebida a 18 m está abaixo da metade dos PV, sem saber o valor exato.</p>`, "path-soul-bleeder"),
    feature("voracious-drain", "Dreno Voraz", 6, `<p>Ao usar Extração, gaste 1 EC: <strong>Devorar</strong> cura 2d8 + INT PV reais; <strong>Transfusão Profana</strong> cura morto-vivo em 2d8 + INT + Proficiência e concede +2 CA até seu turno; <strong>Arrancar Alma</strong> devolve 1 EC e força CON, impondo Desvantagem na próxima salvaguarda antes do seu próximo turno na falha.</p>`, "path-soul-bleeder"),
    feature("blood-pact", "Sangue Pactuado", 10, `<p><strong>Ação Bônus • 1/Descanso Curto ou Longo • 1 minuto.</strong> Perca 1d8 + nível PV, ignorando PV temporários e toda redução/transferência, e escolha dois: recuperar 2 EC; +1d8 no primeiro dano necrótico de cada turno; resistência física; ou Vantagem no primeiro ataque por turno contra criatura abaixo de metade e ignorar meia cobertura.</p>`, "path-soul-bleeder"),
    feature("bloody-execution", "Execução Sangrenta", 15, `<p><strong>Ação • 3 EC • 18 m.</strong> Alvo percebido abaixo da metade faz CON; se Marcado, com Desvantagem. Sofre 6d10 necrótico, metade no sucesso. Se sobreviver após falhar, não recupera PV até o fim do próximo turno.</p>`, "path-soul-bleeder"),
    feature("profane-feast", "Banquete Profano", 18, `<p>Quando sua Marca morrer, inicie sem ação, 1/Descanso Longo, por 1 minuto. Uma vez por turno, cure metade do dano necrótico causado a uma criatura. A primeira Coleta em cada turno não consome uso. A morte da Marca causa 3d6 necrótico a hostis a 3 m; mortes por essa Ruptura não a repetem.</p>`, "path-soul-bleeder")
  ]},
  { key: "path-lord-dead", name: "Caminho do Senhor dos Mortos", description: p("Comanda formações, repõe tropas e eleva o Cadáver Perfeito acima dos demais."), features: [
    feature("necromantic-command", "Comando Necromântico", 3, `<p><strong>Foco de Ataque:</strong> o primeiro servo a acertar alvo escolhido antes do próximo turno dos servos causa +INT; se for a Marca, reduz deslocamento em 3 m.</p><p><strong>Formação Cadavérica:</strong> dois ou mais servos adjacentes recebem +1 CA e atravessam espaços entre si. <strong>Mestre dos Servos:</strong> +1 no limite de Reanimação Menor.</p>`, "path-lord-dead"),
    feature("profane-recruitment", "Recrutamento Profano", 6, `<p>Ao usar Reanimação Menor, gaste +1 EC para reanimar dois cadáveres simultaneamente, respeitando o limite. Quando servo menor for destruído por hostil, sua próxima Reanimação até o fim do próximo turno custa −1 EC, mínimo 1.</p>`, "path-lord-dead"),
    feature("bone-fortress", "Fortaleza de Ossos", 10, `<p><strong>Ação • 2 EC • 18 m.</strong> Crie por até 10 minutos uma muralha de três segmentos conectados de 1,5 m (CA 15, cada um com PV = 5 × nível), ou por 1 minuto um Campo de Ossos de 3 m de raio: terreno difícil; a primeira movimentação voluntária hostil por turno causa 2d6 perfurante. Uma Fortaleza por vez.</p>`, "path-lord-dead"),
    feature("eternal-legacy", "Legado Eterno", 15, `<p>Limite de servos menores +1 adicional. Cadáver Perfeito recebe +1 Herança e uma Característica Superior adaptada do original, nunca Lendária, Mítica ou de Covil.</p>`, "path-lord-dead"),
    feature("tide-of-dead", "Maré dos Mortos", 18, `<p>Exército Infinito não custa EC; Horda recebe +30 PV e +1d8 na Maré Cadavérica. Cadáver Perfeito recebe +1 Herança adicional. Uma vez em cada turno dos servos, emita duas Ordens Necromânticas diferentes.</p>`, "path-lord-dead")
  ]},
  { key: "path-tomb-guardian", name: "Caminho do Guardião do Túmulo", description: p("Usa a morte como muralha para manter aliados e servos do lado de cá do limiar."), features: [
    feature("protective-tomb", "Túmulo Protetor", 3, `<p><strong>Ação Bônus • 1 EC • 18 m.</strong> Você, aliado ou morto-vivo recebe 1d8 + INT + nível em PV temporários até o Descanso Longo. Só pode reaplicar após esses PV serem perdidos.</p><p><strong>Ossos Guardiões — Reação:</strong> quando alvo protegido a 18 m sofre dano, gaste 1 EC para reduzi-lo em 1d8 + INT antes dos PV temporários.</p>`, "path-tomb-guardian"),
    feature("unbreakable-bones", "Ossos Inquebráveis", 6, `<p>Alvo com PV temporários do Túmulo recebe +1 CA; mortos-vivos recebem +2. Quando esses PV chegam a 0, o alvo pode mover 3 m sem Ataques de Oportunidade, uma vez por aplicação.</p>`, "path-tomb-guardian"),
    feature("death-anchor", "Âncora da Morte", 10, `<p>Você e alvos do Túmulo têm Vantagem contra empurrão, atração, queda e medo. Uma vez por rodada, quando protegido for movido contra a vontade, use Reação e 1 EC para cancelar o movimento.</p>`, "path-tomb-guardian"),
    feature("sepulchral-fortress", "Fortaleza Sepulcral", 15, `<p>Com Presença ativa, aliados protegidos dentro da aura recebem +1 CA e resistência necrótica; mortos-vivos também têm Vantagem em salvaguardas de Força e Constituição. Ao usar Ossos Guardiões, +1 EC aplica a mesma redução a um segundo protegido a 6 m atingido pelo mesmo efeito.</p>`, "path-tomb-guardian"),
    feature("tomb-pact", "Pacto do Túmulo", 18, `<p><strong>Reação • 2 EC:</strong> protegido a 18 m que cairia a 0 fica com 1; se morto-vivo, também cura 2d8 + INT. Uma criatura só recebe isso uma vez por Descanso Longo.</p><p><strong>Sentinela Eterno — Ação Bônus, 1/Descanso Longo, 1 minuto:</strong> aliados protegidos resistem a dano físico; Túmulo concede o máximo do d8; Ossos Guardiões reduz 2d8 + INT.</p>`, "path-tomb-guardian")
  ]}
];
