const p = (...parts) => parts.map(text => `<p>${text}</p>`).join("");

const feature = (key, name, level, description, group = "base") => ({
  key, name, level, group, description
});

export const ROGUE_CLASS = {
  key: "ladino",
  name: "Ladino — Nova Era",
  description: `
    <h2>Ladino</h2>
    <blockquote>“Você não vence pela força, mas pelo momento certo.”</blockquote>
    ${p("O Ladino de Nova Era observa, compreende e explora falhas. Seu ciclo é: Observar → Expor → Explorar → Reposicionar.")}
    <h3>Criação da Classe</h3>
    <ul>
      <li><strong>Dado de Vida:</strong> d8</li>
      <li><strong>Atributo Principal:</strong> Destreza</li>
      <li><strong>Defesas:</strong> Armaduras Leves</li>
      <li><strong>Testes de Resistência:</strong> Destreza e Inteligência</li>
      <li><strong>Perícias:</strong> escolha 4 entre Acrobacia, Atletismo, Enganação, Furtividade, Intimidação, Investigação, Intuição, Percepção, Prestidigitação e Sobrevivência.</li>
      <li><strong>CD das Habilidades:</strong> 8 + Proficiência + modificador de Destreza.</li>
    </ul>
    <h3>Ataque Furtivo</h3>
    <p>Níveis 1–4: 1d6; níveis 5–10: 3d6; níveis 11–16: 6d6; níveis 17–20: 9d6.</p>
    <h3>Subclasses</h3>
    <p>Escolha uma subclasse no nível 3. Ela concede novas características nos níveis 3, 9, 13 e 17.</p>
  `
};

export const ROGUE_FEATURES = [
  feature("exposicao", "Exposição", 1, `<p>Cada criatura pode possuir até <strong>3 Exposições para você</strong>. Elas representam postura, ritmo, respiração, padrões defensivos e vícios de movimento que você compreendeu. Permanecem até serem consumidas ou até o fim do combate; trocar de alvo não remove Exposição de outros alvos.</p><p><strong>Analisar:</strong> como Ação Bônus, escolha uma criatura que possa perceber a até 18m e realize Investigação contra CD = 10 + nível da criatura. Em sucesso, obtenha +1 Exposição. Na primeira Análise bem-sucedida, o Mestre revela uma Resistência, Imunidade ou Vulnerabilidade relevante. Se não houver, revela a ausência de proteção ou vulnerabilidade incomum. Análises posteriores geram apenas Exposição.</p>`),
  feature("ataque-furtivo", "Ataque Furtivo — Explorar Brecha", 1, `<p>Uma vez por turno, ao acertar uma criatura Exposta com arma de acuidade ou à distância, pode consumir 1 Exposição para adicionar seu dano de Ataque Furtivo ao ataque.</p><p><strong>Progressão:</strong> 1d6 nos níveis 1–4; 3d6 nos níveis 5–10; 6d6 nos níveis 11–16; 9d6 nos níveis 17–20.</p>`),
  feature("danca-das-laminas", "Dança das Lâminas", 1, `<p><strong>Lâmina de Teste:</strong> uma vez por turno, ao acertar uma criatura com uma adaga e não consumir Exposição nesse ataque, recebe +1 Exposição contra ela. Isso não revela propriedades.</p><p><strong>Passo Cortante:</strong> depois de realizar um ataque corpo a corpo com uma adaga, se possuir pelo menos 3m de deslocamento restante, pode gastar até esses 3m para afastar-se daquele alvo sem provocar ataque de oportunidade dele.</p>`),
  feature("especialista", "Especialista", 2, p("Escolha duas perícias nas quais seja proficiente. Seu bônus de Proficiência é dobrado nos testes realizados com elas.")),
  feature("ponto-cego", "Ponto Cego", 2, p("Uma vez por turno, após consumir pelo menos 1 Exposição durante seu turno, pode realizar Hide como Ação Bônus até o final daquele turno, desde que exista uma condição válida para se esconder.")),
  feature("ataque-extra", "Ataque Extra", 5, p("Ao realizar a ação Atacar, realiza dois ataques em vez de um. O Ataque Furtivo aumenta para 3d6.")),
  feature("exploracao-tecnica", "Exploração Técnica", 6, `<p>Ao realizar Ataque Furtivo, pode consumir 2 Exposições, em vez de 1, para aplicar uma Técnica de Exploração. O dano ocorre normalmente; escolha apenas uma técnica por Ataque Furtivo.</p><ul><li><strong>Perfuração Precisa:</strong> o dano do Ataque Furtivo ignora Resistência ao tipo de dano da arma.</li><li><strong>Quebra de Ritmo:</strong> o alvo não pode realizar Reações até o início do próximo turno dele.</li><li><strong>Corte de Passo:</strong> o deslocamento do alvo é reduzido em 3m até o início do seu próximo turno.</li></ul>`),
  feature("evasao-calculada", "Evasão Calculada", 7, p("Quando realizar um teste de resistência de Destreza contra um efeito originado diretamente por uma criatura contra a qual possua ao menos 1 Exposição: em sucesso, não sofre dano; em falha, sofre metade. A Exposição não é consumida.")),
  feature("maestria", "Maestria", 10, `<p><strong>Especialista Superior:</strong> escolha mais duas perícias nas quais seja proficiente. Seu bônus de Proficiência é dobrado nelas.</p><p><strong>Competência Confiável:</strong> em testes com perícias nas quais possua Especialização, resultados no d20 inferiores a 10 contam como 10.</p>`),
  feature("leitura-completa", "Leitura Completa", 11, `<p>Enquanto possuir 3 Exposições contra uma criatura:</p><ul><li>seu primeiro ataque contra ela em cada turno recebe +2 para acertar;</li><li>você recebe +2 nos testes de resistência provocados diretamente por ela;</li><li>ela não pode obter vantagem em ataques contra você.</li></ul><p>Os benefícios não consomem Exposição e terminam imediatamente se você ficar abaixo de 3. O Ataque Furtivo aumenta para 6d6.</p>`),
  feature("instinto-perigo", "Instinto de Perigo", 14, `<p><strong>Experiência de Campo:</strong> vantagem para detectar, compreender e desarmar armadilhas e identificar emboscadas.</p><p><strong>Pressentimento:</strong> antes de entrar voluntariamente em área com perigo oculto perceptível, o Mestre pode fazer secretamente Percepção ou Investigação. Em sucesso, você percebe que algo está errado, sem necessariamente descobrir a natureza do perigo.</p><p><strong>Reação Instintiva:</strong> quando armadilha ou perigo ambiental perceptível for acionado a até 3m, pode usar sua Reação para mover até metade do deslocamento antes da resolução. Esse movimento pode provocar ataques de oportunidade.</p>`),
  feature("golpe-decifrado", "Golpe Decifrado", 15, p("Enquanto possuir 3 Exposições contra uma criatura, uma vez por turno, ao acertá-la com ataque de arma, causa +2d6. Esse dano não é Ataque Furtivo e não consome Exposição.")),
  feature("antecipacao", "Antecipação", 18, `<p>Enquanto estiver em Leitura Completa contra uma criatura, quando ela declarar uma ação perceptível, pode usar sua Reação antes da resolução:</p><ul><li><strong>Antecipar Golpe:</strong> +4 CA contra um ataque declarado contra você.</li><li><strong>Antecipar Movimento:</strong> mova até metade do deslocamento antes do movimento voluntário dela, sem provocar ataque de oportunidade daquela criatura.</li><li><strong>Antecipar Técnica:</strong> +4 em um teste de resistência provocado por ela.</li></ul><p>Nenhuma opção consome Exposição.</p>`),
  feature("olhar-predador", "Olhar do Predador", 20, `<p><strong>Primeira Impressão:</strong> quando a Iniciativa é rolada, escolha uma criatura perceptível e realize Analisar sem gastar ação. Em sucesso, ela recebe 3 Exposições em vez de 1.</p><p><strong>Nenhum Erro Passa Despercebido:</strong> uma vez por rodada, quando criatura perceptível sem Leitura Completa errar um ataque ou falhar em resistência ou teste durante combate, obtenha +1 Exposição contra ela, sem ação ou Reação.</p><p><strong>Falha Fatal:</strong> uma vez por Descanso Longo, ao acertar Ataque Furtivo contra criatura em Leitura Completa, consuma as 3 Exposições. Apenas os dados do Ataque Furtivo causam valor máximo; escolha ainda uma Técnica de Exploração, aplicada sem custo adicional.</p>`)
];

export const ROGUE_SUBCLASSES = [
  { key: "fantasma", name: "Fantasma", description: p("Segurança através de posicionamento e manipulação da atenção."), features: [
    feature("entre-olhares", "Entre Olhares", 3, `<p>Criaturas contra as quais possua Exposição sofrem -2 em Percepção para detectar você. Uma vez por turno, pode atravessar até 3m de espaço exposto entre posições válidas para se esconder sem revelar automaticamente sua posição para elas.</p><p><strong>Ponto Cego Aprimorado:</strong> +2 em Furtividade ao usar Ponto Cego contra criatura Exposta.</p>`, "fantasma"),
    feature("presenca-inalcancavel", "Presença Inalcançável", 9, p("Quando criatura contra a qual possua Exposição errar um ataque contra você, use sua Reação para mover até metade do deslocamento sem provocar ataques de oportunidade dela. Se terminar em posição válida, pode realizar Hide como parte da Reação. Não consome Exposição."), "fantasma"),
    feature("desvanecer", "Desvanecer", 13, p("Uma vez por rodada, ao usar Ponto Cego ou Presença Inalcançável para tentar se esconder, escolha criatura Exposta. Pode realizar Hide contra ela mesmo sem cobertura ou obscurecimento suficientes. Em sucesso, é considerado Invisível para ela até o início do seu próximo turno, até atacar, conjurar magia ou revelar claramente sua posição. Não consome Exposição."), "fantasma"),
    feature("forma-fantasma", "Forma Fantasma", 17, `<p>Como Ação Bônus, entra em Forma Fantasma por 1 minuto. Uso: 1 vez por Descanso Longo.</p><ul><li><strong>Ponto Morto:</strong> Ponto Cego permite Hide contra criaturas Expostas sem cobertura suficiente.</li><li><strong>Sem Rastro:</strong> remove o limite de 3m de Entre Olhares, se terminar em posição válida.</li><li><strong>Nunca Esteve Aqui:</strong> Presença Inalcançável move todo o deslocamento.</li><li><strong>Ausência:</strong> Hide bem-sucedido pode torná-lo Invisível para todas as criaturas Expostas que não o detectarem.</li></ul>`, "fantasma")
  ]},
  { key: "assassino", name: "Assassino", description: p("Preparar, esperar e transformar Exposição em execução."), features: [
    feature("brecha-mortal", "Brecha Mortal", 3, `<p>Uma vez por turno, ao aplicar Ataque Furtivo, pode consumir até 2 Exposições adicionais. Cada uma causa +1d6.</p><p><strong>Ferida Profunda:</strong> se consumir ao menos 1 Exposição adicional, o alvo faz resistência de Constituição contra CD = 8 + Proficiência + Destreza. Em falha, não pode recuperar PV até o início do seu próximo turno.</p>`, "assassino"),
    feature("janela-execucao", "Janela de Execução", 9, `<p>Ao atacar escondido, se possuir ao menos 2 Exposições contra o alvo, seus ataques contra ele causam crítico em 19–20 até o final do turno.</p><p><strong>Preservar a Brecha:</strong> quando obtiver crítico com Janela de Execução e usar Brecha Mortal, a primeira Exposição adicional não é consumida.</p>`, "assassino"),
    feature("paciencia-mortal", "Paciência Mortal", 13, `<p>Se iniciar seu turno com 3 Exposições contra uma criatura, não causar dano a ela e terminar ainda com as 3, prepara Paciência Mortal até o final do próximo turno ou até ficar abaixo de 3. Apenas uma preparação por vez.</p><p><strong>Execução Preparada:</strong> cada Exposição adicional de Brecha Mortal causa +2d6.</p><p><strong>Janela Perfeita:</strong> atacando escondido, crítico em 18–20.</p>`, "assassino"),
    feature("execucao-perfeita", "Execução Perfeita", 17, `<p>Durante Paciência Mortal, cada Exposição adicional de Brecha Mortal causa +3d6 e a margem de crítico permanece 18–20.</p><p>Ao acertar o Ataque Furtivo que consome Paciência Mortal, o alvo faz resistência de Constituição contra CD = 8 + Proficiência + Destreza. Em falha, somente os dados do Ataque Furtivo causam valor máximo; em sucesso, são rolados normalmente.</p>`, "assassino")
  ]},
  { key: "rastreador", name: "Rastreador", description: p("Exposição constrói Pressão. Perseguição mantém Pressão. Pressão recompensa permanência."), features: [
    feature("instinto-caca", "Instinto de Caça", 3, `<p>Quando criatura receber sua primeira Exposição, pode escolhê-la como Presa, sem ação. Apenas uma Presa por vez.</p><p><strong>Rastro Conhecido:</strong> enquanto a Presa possuir Exposição, vantagem em Percepção e Sobrevivência para encontrá-la e rastreá-la.</p><p><strong>Exposição Persistente:</strong> perder visão, Hide, Invisibilidade ou distância não remove automaticamente Exposição. Se escapar do encontro, pode manter 1 Exposição até Descanso Longo, nova Presa ou abandono.</p><p><strong>Pressão da Caçada:</strong> obter nova Exposição aumenta a Pressão em 1 estágio. O máximo é limitado pela Exposição: I/II/III. Uma vez por turno, ataque de arma causa +1d6/+2d6/+3d6. Um turno sem causar dano reduz a Pressão em 1; fuga completa encerra Pressão.</p>`, "rastreador"),
    feature("cacada-persistente", "Caçada Persistente", 9, `<p>Quando a Presa realizar movimento voluntário perceptível, use sua Reação após o movimento para mover até metade do deslocamento em direção a ela, sem provocar ataques de oportunidade da Presa. Funciona contra Disengage; não contra movimento forçado ou teleporte.</p><p><strong>Passo do Perseguidor:</strong> uma vez por turno, acerto com adaga permite mover 1,5m em direção à Presa sem gastar deslocamento, se ainda possuir 3m.</p><p><strong>Adaptação:</strong> em Pressão II, o primeiro ataque da Presa por rodada sofre -2; em III, os dois primeiros sofrem -2, enquanto puder percebê-la.</p>`, "rastreador"),
    feature("ritmo-caca", "Ritmo de Caça", 13, `<p>Entra em Ritmo de Caça somente com 3 Exposições + Pressão III.</p><p><strong>Presença da Presa:</strong> sabe se Presa escondida ou Invisível está a até 9m, sem saber a posição.</p><p><strong>Pressão Ininterrupta:</strong> mantém III sem dano se rastrear com sucesso, terminar a até 3m ou tiver usado Caçada Persistente desde o fim do último turno.</p><p><strong>Perseguição Implacável:</strong> Caçada Persistente move todo o deslocamento. Teleporte perceptível revela direção e, até 18m, distância aproximada; você corre em direção ao destino.</p>`, "rastreador"),
    feature("predador-implacavel", "Predador Implacável", 17, `<p>Funciona apenas em Ritmo de Caça.</p><ul><li><strong>Predação:</strong> Pressão III passa a +4d6.</li><li><strong>Leitura Predatória:</strong> todos os ataques da Presa contra você sofrem -2.</li><li><strong>Perseguição Absoluta:</strong> primeiro uso de Caçada Persistente por rodada não consome Reação.</li><li><strong>Passo Predatório:</strong> Passo do Perseguidor passa para 3m.</li><li><strong>Leitura Incansável:</strong> a primeira Exposição consumida contra a Presa a cada turno pode ser recuperada ao final do turno se causou dano; não conta como nova Exposição.</li></ul>`, "rastreador")
  ]}
];
