import { MODULE_ID } from "../constants.mjs";
import {
  activateAlchemistFormula, alchemistLevel, alchemistSchool, alchemistState, clearAlchemistFormula,
  isNovaEraAlchemist, prepareAlchemistFormula, prepareDangerousExperiment, setReagentPoints,
  toggleAlchemistReserve, updateAlchemistState
} from "../alchemist/core-automation.mjs";

const openPanels=new Map();
const FoundryApplication=globalThis.Application??foundry?.appv1?.api?.Application;
const ART_ROOT=`modules/${MODULE_ID}/assets/ui/alchemist/maleta-v1`;
const ICON=`${ART_ROOT}/maleta-preparada.png`;
function rootOf(app,html){return html?.querySelector?html:html?.[0]?.querySelector?html[0]:app.element?.[0]??app.element??null;}
function keyOf(item){return item?.getFlag?.(MODULE_ID,"contentKey")??"";}
function escape(value){return foundry.utils.escapeHTML(String(value??""));}
function mode(actor,state){if(state.improvised)return"unstable";if(!state.points)return"inert";if(alchemistLevel(actor)>=20&&state.perfectFormulaSlot!==null)return"masterwork";return"prepared";}
function schoolMode(actor){const key=keyOf(alchemistSchool(actor));return key.includes("biomancer")?"biomancer":key.includes("artificer")?"artificer":"transmuter";}
function titleMode(value){return({inert:"MATÉRIA EM REPOUSO",prepared:"FÓRMULAS EM EQUILÍBRIO",unstable:"EXPERIMENTAÇÃO PERIGOSA",masterwork:"OBRA-PRIMA ALQUÍMICA"})[value];}
function bubbles(){return Array.from({length:24},(_,i)=>`<i style="--x:${31+(i*17)%38}%;--size:${3+i%5}px;--dur:${4+i%6}s;--delay:${-(i*.53)}s"></i>`).join("");}
function formulaName(actor,formula){if(!formula)return"Espaço vazio";return formula.label||formula.projectName||actor.items.find(item=>keyOf(item)===formula.projectKey)?.name||"Fórmula";}

function markup(app){
  const actor=app.actor,state=alchemistState(actor),visual=mode(actor,state),selected=Number.isInteger(app.selectedSlot)?app.selectedSlot:state.prepared.findIndex(Boolean),formula=selected>=0?state.prepared[selected]:null;
  const formulas=Array.from({length:9},(_,index)=>{const entry=state.prepared[index],locked=index>=state.capacity,active=index===selected;return`<button class="ne-alchemy-formula ${entry?"filled":""} ${locked?"locked":""} ${active?"selected":""}" data-action="slot" data-slot="${index}" ${locked?"disabled":""} title="${escape(formulaName(actor,entry))}"><span>${index+1}</span><small>${entry?escape(formulaName(actor,entry)).slice(0,16):""}</small></button>`;}).join("");
  const reserves=Array.from({length:Math.max(3,state.reserveMaximum)},(_,index)=>`<button class="ne-alchemy-reserve ${index<state.reserves?"full":""} ${index>=state.reserveMaximum?"locked":""}" data-action="reserve" data-reserve="${index}" ${index>=state.reserveMaximum?"disabled":""}><span>${index<state.reserves?"SELADA":"VAZIA"}</span></button>`).join("");
  const arts=[["inert","maleta-inerte.png"],["prepared","maleta-preparada.png"],["unstable","maleta-instavel.png"],["masterwork","maleta-obra-prima.png"]].map(([name,file])=>`<img class="ne-alchemy-art ${visual===name?"visible":""}" src="${ART_ROOT}/${file}" alt="Maleta ${name}">`).join("");
  const project=formula?actor.items.find(item=>keyOf(item)===formula.projectKey)??game.items.find(item=>keyOf(item)===formula.projectKey):null;
  const detail=formula?`<section class="ne-alchemy-detail"><h3>${escape(formulaName(actor,formula))}</h3><div><span>${formula.cost} PR</span><span>${escape(formula.container)}</span><span>${formula.modifiers.length?escape(formula.modifiers.join(" · ")):"Sem modificador"}</span></div><p>${project?.system?.description?.value??""}</p></section>`:`<section class="ne-alchemy-detail empty"><h3>Escolha um encaixe vazio</h3><p>Prepare uma configuração do Diário para deixá-la pronta para a missão.</p></section>`;
  const school=alchemistSchool(actor)?.name??"Escola ainda não escolhida";
  return`<section class="nova-era ne-alchemy-case" data-mode="${visual}" data-school="${schoolMode(actor)}" data-motion="${globalThis.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches?"off":"on"}" style="--pr:${state.maximum?100*state.points/state.maximum:0}">
    <header><div>A L Q U I M I S T A</div><h2>Maleta de Síntese</h2><p>${escape(school)} · Nível ${alchemistLevel(actor)}</p><strong>${titleMode(visual)}</strong></header>
    <div class="ne-alchemy-stage"><div class="ne-alchemy-ring"></div><div class="ne-alchemy-halo"></div><div class="ne-alchemy-vapour"></div><div class="ne-alchemy-art-stack">${arts}</div><div class="ne-alchemy-bubbles">${bubbles()}</div><div class="ne-alchemy-readout"><span>${state.points}</span><i> / ${state.maximum}</i><small>PONTOS DE REAGENTE</small></div></div>
    <div class="ne-alchemy-meter"><i></i></div><div class="ne-alchemy-resource"><button data-action="minus" ${state.points<=0?"disabled":""}>−</button><span>RESERVA DE REAGENTES</span><button data-action="plus" ${state.points>=state.maximum?"disabled":""}>+</button></div>
    <div class="ne-alchemy-section-head"><span>FÓRMULAS PREPARADAS</span><span>${state.prepared.filter(Boolean).length} / ${state.capacity}</span></div><div class="ne-alchemy-formulas">${formulas}</div>
    <div class="ne-alchemy-section-head"><span>RESERVAS CATALÍTICAS</span><span>${state.improvised?"PRESSÃO CRÍTICA":"PRESSÃO SEGURA"}</span></div><div class="ne-alchemy-reserves">${reserves}</div>
    <div class="ne-alchemy-commands"><button data-action="prepare"><b>Preparar fórmula</b><small>CONFIGURAR ENCAIXE</small></button><button data-action="activate" ${formula?"":"disabled"}><b>Ativar fórmula</b><small>${formula?`${formula.cost} PR`:"ESCOLHA UM ENCAIXE"}</small></button><button data-action="experiment" ${alchemistLevel(actor)>=2?"":"disabled"}><b>Experimentar</b><small>AÇÃO BÔNUS · RISCO</small></button><button data-action="activate-experiment" ${state.improvised?"":"disabled"}><b>Usar improviso</b><small>${state.improvised?`${state.improvised.cost} PR`:"NENHUM PREPARADO"}</small></button></div>
    ${detail}<div class="ne-alchemy-tools"><button data-action="journal">📖 Diário de Pesquisa</button><button data-action="perfect" ${formula&&alchemistLevel(actor)>=20?"":"disabled"}>✦ Marcar Fórmula Perfeita</button><button data-action="clear" ${formula?"":"disabled"}>× Liberar encaixe</button></div>
    <div class="ne-alchemy-notice" role="status">${state.improvised?`Improviso pronto: ${escape(formulaName(actor,state.improvised))}`:"A matéria aguarda uma instrução precisa."}</div><footer>A matéria obedece a quem conhece seu verdadeiro nome.</footer>
  </section>`;
}

async function showJournal(actor){const projects=actor.items.filter(item=>Number(item.getFlag(MODULE_ID,"grade")??0)>0).sort((a,b)=>Number(a.getFlag(MODULE_ID,"grade"))-Number(b.getFlag(MODULE_ID,"grade"))||a.name.localeCompare(b.name));new Dialog({title:`Diário de Pesquisa — ${actor.name}`,content:`<section class="nova-era ne-alchemy-journal">${projects.map(item=>`<article><img src="${item.img}"><div><h3>${escape(item.name)}</h3><small>Grau ${["","I","II","III","IV"][Number(item.getFlag(MODULE_ID,"grade"))]} · ${item.getFlag(MODULE_ID,"reagentCost")} PR</small>${item.system.description.value}</div></article>`).join("")||"<p>Nenhum Projeto registrado.</p>"}</section>`,buttons:{close:{label:"Fechar"}}},{width:620,height:720,resizable:true}).render(true);}

function panelElement(app){const wrapper=document.createElement("div");wrapper.innerHTML=markup(app);const panel=wrapper.firstElementChild;panel.addEventListener("click",async event=>{const button=event.target.closest("button[data-action]");if(!button||button.disabled)return;const action=button.dataset.action,state=alchemistState(app.actor);if(action==="minus")await setReagentPoints(app.actor,state.points-1);if(action==="plus")await setReagentPoints(app.actor,state.points+1);if(action==="slot"){const index=Number(button.dataset.slot);if(state.prepared[index])app.selectedSlot=index;else if(await prepareAlchemistFormula(app.actor,index))app.selectedSlot=index;app.render(false);}if(action==="reserve")await toggleAlchemistReserve(app.actor,Number(button.dataset.reserve));if(action==="prepare"){const index=state.prepared.findIndex(entry=>!entry);if(await prepareAlchemistFormula(app.actor,index))app.selectedSlot=index;}if(action==="activate")await activateAlchemistFormula(app.actor,app.selectedSlot);if(action==="experiment")await prepareDangerousExperiment(app.actor);if(action==="activate-experiment")await activateAlchemistFormula(app.actor,null,{improvised:true});if(action==="journal")await showJournal(app.actor);if(action==="perfect")await updateAlchemistState(app.actor,{perfectFormulaSlot:app.selectedSlot},"Fórmula Perfeita escolhida");if(action==="clear"&&Number.isInteger(app.selectedSlot)){await clearAlchemistFormula(app.actor,app.selectedSlot);app.selectedSlot=null;}});return panel;}

class AlchemistPanelApplication extends FoundryApplication{
  constructor(actor,options={}){super(options);this.actor=actor;this.selectedSlot=null;}
  static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{classes:["nova-era-window","nova-era-alchemist-window"],width:720,height:1000,resizable:true,minimizable:true,popOut:true,scrollY:[".window-content"]},{inplace:false});}
  get id(){return`nova-era-alchemist-${this.actor.id}`;}get title(){return`Maleta de Síntese — ${this.actor.name}`;}async _renderInner(){return globalThis.jQuery(panelElement(this));}async close(options={}){openPanels.delete(this.actor.uuid);return super.close(options);}
}
export function openAlchemistPanel(actor){if(!isNovaEraAlchemist(actor)){ui.notifications.warn("Nova Era: esta ficha não pertence a um Alquimista.");return null;}const existing=openPanels.get(actor.uuid);if(existing?.rendered){existing.bringToTop?.();return existing;}const panel=new AlchemistPanelApplication(actor);openPanels.set(actor.uuid,panel);panel.render(true);return panel;}
function launcher(app,html){const actor=app.actor??app.document;if(!isNovaEraAlchemist(actor))return;const root=rootOf(app,html);if(!root||root.querySelector(".ne-alchemist-launcher"))return;const button=document.createElement("button");button.type="button";button.className="ne-alchemist-launcher";button.innerHTML=`<img src="${ICON}" alt=""><span><strong>Maleta de Síntese</strong><small>Abrir Laboratório Portátil</small></span><i class="fa-solid fa-up-right-from-square"></i>`;button.addEventListener("click",event=>{event.preventDefault();openAlchemistPanel(actor);});const sidebar=root.querySelector(".sheet-body .main-content > .sidebar, .sheet-body .main-content .sidebar, [data-application-part='sidebar']");const portrait=sidebar?.querySelector(".portrait, .profile, .sheet-profile, [data-application-part='portrait']");if(portrait)portrait.after(button);else if(sidebar)sidebar.prepend(button);else root.querySelector(".sheet-body, [data-application-part='body'], .tab-body")?.prepend(button);}
export function refreshAlchemistPanels(){for(const app of openPanels.values())if(app.rendered)app.render(false);}
export function registerAlchemistPanel(){for(const hook of ["renderActorSheet","renderActorSheetV2","renderActorSheet5eCharacter","renderActorSheet5eCharacter2"])Hooks.on(hook,launcher);Hooks.on("novaEraAlchemistChanged",({actor})=>{const app=openPanels.get(actor.uuid);if(app?.rendered)app.render(false);});Hooks.on("deleteActor",actor=>{const app=openPanels.get(actor.uuid);if(app)void app.close();});}
